knp_snappy:
    pdf:
        enabled:    true
        binary:     '/usr/bin/wkhtmltopdf'
        options:
            enable-local-file-access: true
    image:
        enabled:    true
        binary:     '/usr/bin/wkhtmltoimage'
        options:    []
